name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      run-id:
        type: string
        description: Number of the Build and Deploy workflow run


jobs:

  production:
    runs-on: ubuntu-latest
    needs: development
    environment:
      name: 'Production'
      url: ${{ env.SWAGGER_URL }}

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:        
          workflow: workflow_name.yml
          workflow_conclusion: success
          run_id: ${{ github.event.inputs.run-id }}
          name: docker-image
          if_no_artifact_found: fail
        
      - name: Get docker-image
        id: image
        run: cat /docker-image/artifacts/image.txt >> $GITHUB_OUTPUT
        
      - name: Print docker-image
        id: image
        run: echo ${{ steps.image.outputs.image }}
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'github-plugin-appservice'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ steps.image.outputs.image }}